import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';



export const satoshi = localFont({
  src: [
    {
      path: './fonts/satoshi/Satoshi-Regular.woff2',
      weight: '400',
      style: 'normal',
    }
  ],
  variable: '--font-satoshi',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${satoshi.variable} overflow-x-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
